//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public class CollisionHelper
		{
			public static Edges getCollisionEdge(Collision2D collision)
			{
				
				ContactPoint2D contactPoint = collision.contacts [0];
				
				Collider2D thisCollider = contactPoint.otherCollider;
				
				float colliderEdgeRight = thisCollider.transform.position.x + thisCollider.bounds.extents.x - 0.1f;
				float colliderEdgeLeft = thisCollider.transform.position.x - thisCollider.bounds.extents.x + 0.1f;
				float colliderEdgeTop = thisCollider.transform.position.y + thisCollider.bounds.extents.x - 0.1f;
				float colliderEdgeBottom = thisCollider.transform.position.y - thisCollider.bounds.extents.y + 0.1f;
				

				if(colliderEdgeTop < contactPoint.point.y)
				{
					return Edges.TOP;
				}

				if(colliderEdgeRight < contactPoint.point.x)
				{
					return Edges.RIGHT;
				}
				
				if(colliderEdgeLeft > contactPoint.point.x)
				{
					return Edges.LEFT;
				}
				
				if(colliderEdgeBottom > contactPoint.point.y)
				{
					return Edges.BOTTOM;
				}
				
				return Edges.NONE;
			}
		}
}

